FROM microsoft/dotnet:3.0-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 9001

FROM microsoft/dotnet:3.0-sdk AS build
WORKDIR /src
COPY ["PerftEvaluation.Api.csproj", "./"]
RUN dotnet restore "./PerftEvaluation.Api.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "PerftEvaluation.Api.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "PerftEvaluation.Api.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "PerftEvaluation.Api.dll"]
